let sofaData = [
  {
    sku: "9AF4FD",
    name: "Settee Sofa",
    categories: "Big Sofa",
    price: 115,
    discountPrice: 110,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/01.png",
  },
  {
    sku: "9AFFF5",
    name: "Chesterfield",
    categories: "Big Sofa",
    price: 118,
    discountPrice: 112,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/02.png",
  },
  {
    sku: "10ABFF5",
    name: "Loveseat",
    categories: "Big Sofa",
    price: 120,
    discountPrice: 112,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/03.png",
  },
  {
    sku: "10ABG5",
    name: "Chaise Lounge",
    categories: "Big Sofa",
    price: 140,
    discountPrice: 130,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/04.png",
  },
  {
    sku: "115FF5",
    name: "Cabriole",
    categories: "Big Sofa",
    price: 130,
    discountPrice: 122,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/05.png",
  },
  {
    sku: "10AZVF5",
    name: "Daybed",
    categories: "Big Sofa",
    price: 125,
    discountPrice: 118,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/06.png",
  },
  {
    sku: "10DBFM5",
    name: "Mid-century Modern",
    categories: "Big Sofa",
    price: 145,
    discountPrice: 130,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/07.png",
  },
  {
    sku: "10A15GE",
    name: "Divan Sofa",
    categories: "Big Sofa",
    price: 135,
    discountPrice: 125,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/08.png",
  },
  {
    sku: "10A12GE",
    name: "Recamier",
    categories: "Big Sofa",
    price: 105,
    discountPrice: 90,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/09.png",
  },
  {
    sku: "10A19RE",
    name: "Sectional Sofa",
    categories: "Big Sofa",
    price: 150,
    discountPrice: 140,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/10.png",
  },
  {
    sku: "10A11WE",
    name: "Bridgewater Sofa",
    categories: "Big Sofa",
    price: 165,
    discountPrice: 150,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/11.png",
  },
  {
    sku: "10A13PE",
    name: "Rattan Sofa",
    categories: "Big Sofa",
    price: 160,
    discountPrice: 140,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/12.png",
  },
  {
    sku: "10B01RE",
    name: "Tuxedo Sofa",
    categories: "Big Sofa",
    price: 180,
    discountPrice: 155,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/13.png",
  },
  {
    sku: "10B02RE",
    name: "Lawson Sofa",
    categories: "Big Sofa",
    price: 140,
    discountPrice: 120,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/14.png",
  },
  {
    sku: "10B05RE",
    name: "Camelback Sofa",
    categories: "Big Sofa",
    price: 120,
    discountPrice: 110,
    quantity: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/15.png",
  },
];
