let sofaData = [
  {
    id: "a1",
    sku: "A9AF4FD",
    name: "Settee Sofa",
    categories: "Big Sofa",
    price: 115,
    discountPrice: 110,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/01.png",
  },
  {
    id: "a2",
    sku: "A9AFFF5",
    name: "Chesterfield",
    categories: "Big Sofa",
    price: 118,
    discountPrice: 112,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/02.png",
  },
  {
    id: "a3",
    sku: "A10ABFF5",
    name: "Loveseat",
    categories: "Big Sofa",
    price: 120,
    discountPrice: 112,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/03.png",
  },
  {
    id: "a4",
    sku: "A10ABG5",
    name: "Chaise Lounge",
    categories: "Big Sofa",
    price: 140,
    discountPrice: 130,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/04.png",
  },
  {
    id: "a5",
    sku: "A115FF5",
    name: "Cabriole",
    categories: "Big Sofa",
    price: 130,
    discountPrice: 122,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/05.png",
  },
  {
    id: "a6",
    sku: "A10AZVF5",
    name: "Daybed",
    categories: "Big Sofa",
    price: 125,
    discountPrice: 118,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/06.png",
  },
  {
    id: "a7",
    sku: "A10DBFM5",
    name: "Mid-century Modern",
    categories: "Big Sofa",
    price: 145,
    discountPrice: 130,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/07.png",
  },
  {
    id: "a8",
    sku: "A10A15GE",
    name: "Divan Sofa",
    categories: "Big Sofa",
    price: 135,
    discountPrice: 125,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/08.png",
  },
  {
    id: "a9",
    sku: "A10A12GE",
    name: "Recamier",
    categories: "Big Sofa",
    price: 105,
    discountPrice: 90,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/09.png",
  },
  {
    id: "a10",
    sku: "A10A19RE",
    name: "Sectional Sofa",
    categories: "Big Sofa",
    price: 150,
    discountPrice: 140,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/10.png",
  },
  {
    id: "a11",
    sku: "A10A11WE",
    name: "Bridgewater Sofa",
    categories: "Big Sofa",
    price: 165,
    discountPrice: 150,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/11.png",
  },
  {
    id: "a12",
    sku: "A10A13PE",
    name: "Rattan Sofa",
    categories: "Big Sofa",
    price: 160,
    discountPrice: 140,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/12.png",
  },
  {
    id: "a13",
    sku: "A10B01RE",
    name: "Tuxedo Sofa",
    categories: "Big Sofa",
    price: 180,
    discountPrice: 155,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/13.png",
  },
  {
    id: "a14",
    sku: "A10B02RE",
    name: "Lawson Sofa",
    categories: "Big Sofa",
    price: 140,
    discountPrice: 120,
    stock: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/14.png",
  },
  {
    id: "a15",
    sku: "A10B05RE",
    name: "Camelback Sofa",
    categories: "Big Sofa",
    price: 120,
    discountPrice: 110,
    stock: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora temporibus quia perspiciatis non vero autem unde veritatis quasi, quas ab eaque atque dolores reprehenderit quidem dolorum!",
    img: "image/15.png",
  },
];
